// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageType = "Init" | { FloatUpdate: number } | { IntUpdate: number } | { BoolUpdate: boolean } | { GestureUpdate: boolean };