// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageType } from "./MessageType";
import type { Target } from "./Target";

export interface Message { target: Target | null, message: MessageType | null, }